### ISSUE TITLE
About Pattern Recognition Letters

### ISSUE THREAD

**Issue by Jiaquan789** [jpanagos/vsr_phm#1]
Hello, author. I am preparing to submit to Pattern Recognition Letters, but there are discrepancies between the LaTeX format, the journal template, and the official template compared to the published journal. Could you provide a LaTeX template for Pattern Recognition Letters? Thank you.

**Comment by jpanagos** [comment]
Hello, we used the official template found in the journal's webpage.
It appears to have been changed, so I would use the one provided in the [guide for authors](https://www.sciencedirect.com/journal/pattern-recognition-letters/publish/guide-for-authors).
(https://mirrors.ctan.org/macros/latex/contrib/elsarticle.zip)
The published journal will differ from the submitted template due to final typesetting by the Editor.

In any case, I am uploading the one I used for submission (contains additional templates such as authorship confirmation):
[PRLETTERS_LATEX_Template_DC.zip](https://github.com/user-attachments/files/17108847/PRLETTERS_LATEX_Template_DC.zip)
